### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by exgile** [ckmarkoh/neuralart_tensorflow#1]
When i run main.py, it show some error

Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main()
  File "main.py", line 112, in main
    content_img = read_image(CONTENT_IMG)
  File "main.py", line 96, in read_image
    image = image[np.newaxis,:IMAGE_H,:IMAGE_W,:] 
IndexError: too many indices for array

how do i fix it, Thx

**Comment by webmaven** [comment]
@exgile, is this still an issue?

**Comment by AlessioTonioni** [comment]
I had the same problem using anaconda and python 3.5. It seems related to an incorrect configuration of the PIL modules or to the absence of it. 
In my case I have solved this issue installing the 'pillow' module with pip and removing 'PIL'.

**Comment by AlessioTonioni** [comment]
I had the same problem using anaconda with python 3.5. 
The problem is related to the io module of scipy that uses 'PIL' to load and save image, at least in my case the image loaded from the disk was an empty array with only a descriptive header string, that's what caused the error when trying to slice it.
Anyway I have solved installing 'pillow' instead of 'PIL' with pip.

**Comment by francescoagati** [comment]
i have installed pillow but have the same problem. have you change something in the script for use pillow instad of PIL?

**Comment by francescoagati** [comment]
i use python 2.7.6 on bash ubuntu

**Comment by ckmarkoh** [comment]
Now, I replace this line by scipy.misc.imresize(image,(IMAGE_H,IMAGE_W)).
I hope this could solve this issue.
If it can't, it is recommended to use other image-processing libraries such as cv2 or skimage.
So that it can read an image as three dimensional numpy array.

Actually, when I created this project two years ago, I was not familiar with python API for image processing, and I didn't know how to resize image.
